[package]
name = "coding-challenges"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.4"
vector2d = "2.2.0"
rayon = "1.8.1"
num_cpus = "1.16.0"
minifb = "0.25.0"
